version: '3.9'
services:
  database:
    build:
     context: .
     dockerfile: Dockerfile
    logging:
      driver: "none"
    ports:
    - 27017:27017
    volumes:
    - mongodb_data:/data/db

    networks:
      - mongo-net


volumes:
  mongodb_data:
    external:
      name: mongodb_data

networks:
  mongo-net:
    external: true
    name: mongo-net
    driver: bridge