version: '3.9'
services:

  database:
    extends:
      file: ../mongo_service/docker-compose.yml
      service: database

#Service that downloads the data from the ENA
  ena_download_service:
    build:
      context: ..
      dockerfile: DataIngest/ena_download/Dockerfile
    container_name: ena_data_collection
    environment:
      - JSON_FILE=table.txt
      #The location in the bound volume to store the data
      - OUTPUT_DIR=./data/samples/morgan
    depends_on:
      - database
    command:
      python -u ena_download.py
    volumes:
      - ./filereport_read_run_PRJNA82111_json.txt:/ena_download/table.txt
      - ../PipelineOutput:/ena_download/data
      - ../mongo_service/db_interface/pymongoClient:/ena_download/pymongoClient
    networks:
      - mongo-net

#Service that injests the metadata into the database
  metadata_ingest:
    build:
      context: ..
      dockerfile: DataIngest/metadata_ingest/Dockerfile
    container_name: metadata_ingest
    environment:
      - META_FILE=metadata.txt
    depends_on:
      - database
    command: python text_metadata.py
    volumes:
    - ./osccar_prism_metadata.txt:/metadata_ingest/metadata.txt
    - ../mongo_service/db_interface/pymongoClient:/metadata_ingest/pymongoClient
    networks:
      - mongo-net

volumes:
  mongodb_data:
    external:
      name: mongodb_data


networks:
  mongo-net:
    external: true
    name: mongo-net
    driver: bridge
