version: '3.9'
services:
    classification_training:
      image: qiime2/core:2020.8
      container_name: classification_training
      command: bash -c "cd ../app && python -u ClassifierTraining.py"
      volumes:
        - .:/app


